// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ticket.proto

package server

import (
	"context"

	"tickets-hunter/app/ticket/cmd/rpc/internal/logic"
	"tickets-hunter/app/ticket/cmd/rpc/internal/svc"
	"tickets-hunter/app/ticket/cmd/rpc/ticket/rpc"
)

type TicketServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedTicketServiceServer
}

func NewTicketServiceServer(svcCtx *svc.ServiceContext) *TicketServiceServer {
	return &TicketServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取演唱会场次列表 (供 API 层调用)
func (s *TicketServiceServer) GetEventList(ctx context.Context, in *rpc.GetEventListReq) (*rpc.GetEventListResp, error) {
	l := logic.NewGetEventListLogic(ctx, s.svcCtx)
	return l.GetEventList(in)
}

// 获取指定场次的座位图及状态 (供 API 层调用)
func (s *TicketServiceServer) GetSeatList(ctx context.Context, in *rpc.GetSeatListReq) (*rpc.GetSeatListResp, error) {
	l := logic.NewGetSeatListLogic(ctx, s.svcCtx)
	return l.GetSeatList(in)
}

// 锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
func (s *TicketServiceServer) LockSeat(ctx context.Context, in *rpc.LockSeatReq) (*rpc.LockSeatResp, error) {
	l := logic.NewLockSeatLogic(ctx, s.svcCtx)
	return l.LockSeat(in)
}

// 获取座位信息 (供 Order RPC 内部调用)
func (s *TicketServiceServer) GetSeatInfo(ctx context.Context, in *rpc.GetSeatInfoReq) (*rpc.SeatInfo, error) {
	l := logic.NewGetSeatInfoLogic(ctx, s.svcCtx)
	return l.GetSeatInfo(in)
}
