// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package order_main

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	orderMainFieldNames          = builder.RawFieldNames(&OrderMain{})
	orderMainRows                = strings.Join(orderMainFieldNames, ",")
	orderMainRowsExpectAutoSet   = strings.Join(stringx.Remove(orderMainFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	orderMainRowsWithPlaceHolder = strings.Join(stringx.Remove(orderMainFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	orderMainModel interface {
		Insert(ctx context.Context, data *OrderMain) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OrderMain, error)
		FindOneByOrderSn(ctx context.Context, orderSn string) (*OrderMain, error)
		Update(ctx context.Context, data *OrderMain) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOrderMainModel struct {
		conn  sqlx.SqlConn
		table string
	}

	OrderMain struct {
		Id         int64        `db:"id"`
		OrderSn    string       `db:"order_sn"`    // 订单流水号(雪花算法生成)
		UserId     int64        `db:"user_id"`     // 用户ID
		EventId    int64        `db:"event_id"`    // 场次ID
		SeatId     int64        `db:"seat_id"`     // 座位ID
		Section    string       `db:"section"`     // 区域信息
		SeatIndex  int64        `db:"seat_index"`  // Redis Bitmap座位索引
		Amount     int64        `db:"amount"`      // 订单实付金额，以分为单位
		Status     int64        `db:"status"`      // 状态: 10待支付, 20已支付(待出票), 30已出票(已完成)，40超时关闭，51已退款
		ExpireTime time.Time    `db:"expire_time"` // 订单支付过期时间(通常为创建时间+15分钟)
		PayTime    sql.NullTime `db:"pay_time"`    // 实际支付时间
		CreateTime time.Time    `db:"create_time"`
		UpdateTime time.Time    `db:"update_time"`
	}
)

func newOrderMainModel(conn sqlx.SqlConn) *defaultOrderMainModel {
	return &defaultOrderMainModel{
		conn:  conn,
		table: "`order_main`",
	}
}

func (m *defaultOrderMainModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOrderMainModel) FindOne(ctx context.Context, id int64) (*OrderMain, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", orderMainRows, m.table)
	var resp OrderMain
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderMainModel) FindOneByOrderSn(ctx context.Context, orderSn string) (*OrderMain, error) {
	var resp OrderMain
	query := fmt.Sprintf("select %s from %s where `order_sn` = ? limit 1", orderMainRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderSn)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOrderMainModel) Insert(ctx context.Context, data *OrderMain) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, orderMainRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OrderSn, data.UserId, data.EventId, data.SeatId, data.Section, data.SeatIndex, data.Amount, data.Status, data.ExpireTime, data.PayTime)
	return ret, err
}

func (m *defaultOrderMainModel) Update(ctx context.Context, newData *OrderMain) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, orderMainRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.OrderSn, newData.UserId, newData.EventId, newData.SeatId, newData.Section, newData.SeatIndex, newData.Amount, newData.Status, newData.ExpireTime, newData.PayTime, newData.Id)
	return err
}

func (m *defaultOrderMainModel) tableName() string {
	return m.table
}
