// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order_msg.proto

package order_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatId        int64                  `protobuf:"varint,4,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	SeatIndex     int64                  `protobuf:"varint,6,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	Amount        int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,8,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderMsg) Reset() {
	*x = CreateOrderMsg{}
	mi := &file_order_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderMsg) ProtoMessage() {}

func (x *CreateOrderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_order_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderMsg.ProtoReflect.Descriptor instead.
func (*CreateOrderMsg) Descriptor() ([]byte, []int) {
	return file_order_msg_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderMsg) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *CreateOrderMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderMsg) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateOrderMsg) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *CreateOrderMsg) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *CreateOrderMsg) GetSeatIndex() int64 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *CreateOrderMsg) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderMsg) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

var File_order_msg_proto protoreflect.FileDescriptor

const file_order_msg_proto_rawDesc = "" +
	"\n" +
	"\x0forder_msg.proto\x12\torder_msg\"\xea\x01\n" +
	"\x0eCreateOrderMsg\x12\x19\n" +
	"\border_sn\x18\x01 \x01(\tR\aorderSn\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12\x17\n" +
	"\aseat_id\x18\x04 \x01(\x03R\x06seatId\x12\x18\n" +
	"\asection\x18\x05 \x01(\tR\asection\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x06 \x01(\x03R\tseatIndex\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x1f\n" +
	"\vexpire_time\x18\b \x01(\x03R\n" +
	"expireTimeB\rZ\v./order_msgb\x06proto3"

var (
	file_order_msg_proto_rawDescOnce sync.Once
	file_order_msg_proto_rawDescData []byte
)

func file_order_msg_proto_rawDescGZIP() []byte {
	file_order_msg_proto_rawDescOnce.Do(func() {
		file_order_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_msg_proto_rawDesc), len(file_order_msg_proto_rawDesc)))
	})
	return file_order_msg_proto_rawDescData
}

var file_order_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_msg_proto_goTypes = []any{
	(*CreateOrderMsg)(nil), // 0: order_msg.CreateOrderMsg
}
var file_order_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_msg_proto_init() }
func file_order_msg_proto_init() {
	if File_order_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_msg_proto_rawDesc), len(file_order_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_msg_proto_goTypes,
		DependencyIndexes: file_order_msg_proto_depIdxs,
		MessageInfos:      file_order_msg_proto_msgTypes,
	}.Build()
	File_order_msg_proto = out.File
	file_order_msg_proto_goTypes = nil
	file_order_msg_proto_depIdxs = nil
}
