// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: order.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CreateOrderReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrderReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CreateOrderReqMultiError,
// or nil if none found.
func (m *CreateOrderReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrderReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() <= 0 {
		err := CreateOrderReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetEventId() <= 0 {
		err := CreateOrderReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSeatId() <= 0 {
		err := CreateOrderReqValidationError{
			field:  "SeatId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateOrderReqMultiError(errors)
	}

	return nil
}

// CreateOrderReqMultiError is an error wrapping multiple validation errors
// returned by CreateOrderReq.ValidateAll() if the designated constraints
// aren't met.
type CreateOrderReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrderReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrderReqMultiError) AllErrors() []error { return m }

// CreateOrderReqValidationError is the validation error returned by
// CreateOrderReq.Validate if the designated constraints aren't met.
type CreateOrderReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrderReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrderReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrderReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrderReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrderReqValidationError) ErrorName() string { return "CreateOrderReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateOrderReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrderReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrderReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrderReqValidationError{}

// Validate checks the field values on CreateOrderResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateOrderResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateOrderResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateOrderRespMultiError, or nil if none found.
func (m *CreateOrderResp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateOrderResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderSn

	// no validation rules for Amount

	// no validation rules for ExpireTime

	if len(errors) > 0 {
		return CreateOrderRespMultiError(errors)
	}

	return nil
}

// CreateOrderRespMultiError is an error wrapping multiple validation errors
// returned by CreateOrderResp.ValidateAll() if the designated constraints
// aren't met.
type CreateOrderRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateOrderRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateOrderRespMultiError) AllErrors() []error { return m }

// CreateOrderRespValidationError is the validation error returned by
// CreateOrderResp.Validate if the designated constraints aren't met.
type CreateOrderRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateOrderRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateOrderRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateOrderRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateOrderRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateOrderRespValidationError) ErrorName() string { return "CreateOrderRespValidationError" }

// Error satisfies the builtin error interface
func (e CreateOrderRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateOrderResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateOrderRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateOrderRespValidationError{}

// Validate checks the field values on GetOrderDetailReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetOrderDetailReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOrderDetailReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOrderDetailReqMultiError, or nil if none found.
func (m *GetOrderDetailReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOrderDetailReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOrderSn()) < 1 {
		err := GetOrderDetailReqValidationError{
			field:  "OrderSn",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := GetOrderDetailReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetOrderDetailReqMultiError(errors)
	}

	return nil
}

// GetOrderDetailReqMultiError is an error wrapping multiple validation errors
// returned by GetOrderDetailReq.ValidateAll() if the designated constraints
// aren't met.
type GetOrderDetailReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOrderDetailReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOrderDetailReqMultiError) AllErrors() []error { return m }

// GetOrderDetailReqValidationError is the validation error returned by
// GetOrderDetailReq.Validate if the designated constraints aren't met.
type GetOrderDetailReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrderDetailReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrderDetailReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrderDetailReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrderDetailReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrderDetailReqValidationError) ErrorName() string {
	return "GetOrderDetailReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrderDetailReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrderDetailReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrderDetailReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrderDetailReqValidationError{}

// Validate checks the field values on GetOrderDetailResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetOrderDetailResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetOrderDetailResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetOrderDetailRespMultiError, or nil if none found.
func (m *GetOrderDetailResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetOrderDetailResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderSn

	// no validation rules for EventId

	// no validation rules for SeatId

	// no validation rules for Amount

	// no validation rules for Status

	// no validation rules for ExpireTime

	// no validation rules for CreateTime

	if len(errors) > 0 {
		return GetOrderDetailRespMultiError(errors)
	}

	return nil
}

// GetOrderDetailRespMultiError is an error wrapping multiple validation errors
// returned by GetOrderDetailResp.ValidateAll() if the designated constraints
// aren't met.
type GetOrderDetailRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetOrderDetailRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetOrderDetailRespMultiError) AllErrors() []error { return m }

// GetOrderDetailRespValidationError is the validation error returned by
// GetOrderDetailResp.Validate if the designated constraints aren't met.
type GetOrderDetailRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetOrderDetailRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetOrderDetailRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetOrderDetailRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetOrderDetailRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetOrderDetailRespValidationError) ErrorName() string {
	return "GetOrderDetailRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetOrderDetailRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetOrderDetailResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetOrderDetailRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetOrderDetailRespValidationError{}

// Validate checks the field values on SagaOrderReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SagaOrderReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SagaOrderReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SagaOrderReqMultiError, or
// nil if none found.
func (m *SagaOrderReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SagaOrderReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderSn

	// no validation rules for UserId

	// no validation rules for Amount

	// no validation rules for SeatId

	// no validation rules for EventId

	// no validation rules for Section

	// no validation rules for SeatIndex

	if len(errors) > 0 {
		return SagaOrderReqMultiError(errors)
	}

	return nil
}

// SagaOrderReqMultiError is an error wrapping multiple validation errors
// returned by SagaOrderReq.ValidateAll() if the designated constraints aren't met.
type SagaOrderReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SagaOrderReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SagaOrderReqMultiError) AllErrors() []error { return m }

// SagaOrderReqValidationError is the validation error returned by
// SagaOrderReq.Validate if the designated constraints aren't met.
type SagaOrderReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SagaOrderReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SagaOrderReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SagaOrderReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SagaOrderReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SagaOrderReqValidationError) ErrorName() string { return "SagaOrderReqValidationError" }

// Error satisfies the builtin error interface
func (e SagaOrderReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSagaOrderReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SagaOrderReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SagaOrderReqValidationError{}

// Validate checks the field values on SagaOrderResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SagaOrderResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SagaOrderResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SagaOrderRespMultiError, or
// nil if none found.
func (m *SagaOrderResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SagaOrderResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return SagaOrderRespMultiError(errors)
	}

	return nil
}

// SagaOrderRespMultiError is an error wrapping multiple validation errors
// returned by SagaOrderResp.ValidateAll() if the designated constraints
// aren't met.
type SagaOrderRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SagaOrderRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SagaOrderRespMultiError) AllErrors() []error { return m }

// SagaOrderRespValidationError is the validation error returned by
// SagaOrderResp.Validate if the designated constraints aren't met.
type SagaOrderRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SagaOrderRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SagaOrderRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SagaOrderRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SagaOrderRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SagaOrderRespValidationError) ErrorName() string { return "SagaOrderRespValidationError" }

// Error satisfies the builtin error interface
func (e SagaOrderRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSagaOrderResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SagaOrderRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SagaOrderRespValidationError{}
