// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderservice

import (
	"context"
	rpc2 "tickets-hunter/app/order/cmd/rpc/order/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOrderReq     = rpc2.CreateOrderReq
	CreateOrderResp    = rpc2.CreateOrderResp
	GetOrderDetailReq  = rpc2.GetOrderDetailReq
	GetOrderDetailResp = rpc2.GetOrderDetailResp
	SagaOrderReq       = rpc2.SagaOrderReq
	SagaOrderResp      = rpc2.SagaOrderResp

	OrderService interface {
		// 创建抢票订单 (包含调用 Ticket RPC 锁座逻辑)
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		// 获取订单详情
		GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error)
		// Saga 步骤2 正向操作：确认出票
		IssueTicket(ctx context.Context, in *SagaOrderReq, opts ...grpc.CallOption) (*SagaOrderResp, error)
		// Saga 步骤2 补偿操作：回滚出票
		RollbackTicket(ctx context.Context, in *SagaOrderReq, opts ...grpc.CallOption) (*SagaOrderResp, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// 创建抢票订单 (包含调用 Ticket RPC 锁座逻辑)
func (m *defaultOrderService) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := rpc2.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

// 获取订单详情
func (m *defaultOrderService) GetOrderDetail(ctx context.Context, in *GetOrderDetailReq, opts ...grpc.CallOption) (*GetOrderDetailResp, error) {
	client := rpc2.NewOrderServiceClient(m.cli.Conn())
	return client.GetOrderDetail(ctx, in, opts...)
}

// Saga 步骤2 正向操作：确认出票
func (m *defaultOrderService) IssueTicket(ctx context.Context, in *SagaOrderReq, opts ...grpc.CallOption) (*SagaOrderResp, error) {
	client := rpc2.NewOrderServiceClient(m.cli.Conn())
	return client.IssueTicket(ctx, in, opts...)
}

// Saga 步骤2 补偿操作：回滚出票
func (m *defaultOrderService) RollbackTicket(ctx context.Context, in *SagaOrderReq, opts ...grpc.CallOption) (*SagaOrderResp, error) {
	client := rpc2.NewOrderServiceClient(m.cli.Conn())
	return client.RollbackTicket(ctx, in, opts...)
}
