// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type PayReq struct {
	OrderSn string `json:"order_sn"` // 只需要传订单号，金额和座位让后端自己查防篡改
}

type PayResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}
