// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	ticket "tickets-hunter/app/ticket/cmd/api/internal/handler/ticket"
	"tickets-hunter/app/ticket/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取上架的演唱会场次列表
				Method:  http.MethodGet,
				Path:    "/events",
				Handler: ticket.GetEventListHandler(serverCtx),
			},
			{
				// 获取指定场次的座位图及状态
				Method:  http.MethodGet,
				Path:    "/seats",
				Handler: ticket.GetSeatListHandler(serverCtx),
			},
			{
				// 获取指定场次的座位图（BitMap形式）及状态
				Method:  http.MethodGet,
				Path:    "/seats/bitmap",
				Handler: ticket.GetSeatBitMapHandler(serverCtx),
			},
		},
		rest.WithPrefix("/ticket/v1"),
	)
}
