// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"
	logic2 "tickets-hunter/app/order/cmd/rpc/internal/logic"
	"tickets-hunter/app/order/cmd/rpc/internal/svc"
	rpc2 "tickets-hunter/app/order/cmd/rpc/order/rpc"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	rpc2.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建抢票订单 (包含调用 Ticket RPC 锁座逻辑)
func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *rpc2.CreateOrderReq) (*rpc2.CreateOrderResp, error) {
	l := logic2.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

// 获取订单详情
func (s *OrderServiceServer) GetOrderDetail(ctx context.Context, in *rpc2.GetOrderDetailReq) (*rpc2.GetOrderDetailResp, error) {
	l := logic2.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}
