// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package server

import (
	"context"
	rpc2 "tickets-hunter/app/payment/cmd/rpc/payment/rpc"

	"tickets-hunter/app/payment/cmd/rpc/internal/logic"
	"tickets-hunter/app/payment/cmd/rpc/internal/svc"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	rpc2.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

// Saga 步骤1 正向操作：扣减余额
func (s *PaymentServer) Deduct(ctx context.Context, in *rpc2.SagaPayReq) (*rpc2.SagaPayResp, error) {
	l := logic.NewDeductLogic(ctx, s.svcCtx)
	return l.Deduct(in)
}

// Saga 步骤2 补偿操作：退还余额
func (s *PaymentServer) Refund(ctx context.Context, in *rpc2.SagaPayReq) (*rpc2.SagaPayResp, error) {
	l := logic.NewRefundLogic(ctx, s.svcCtx)
	return l.Refund(in)
}

// API 层调用的支付接口
func (s *PaymentServer) Pay(ctx context.Context, in *rpc2.PayReq) (*rpc2.PayResp, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}
