// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"tickets-hunter/app/usercenter/cmd/rpc/internal/logic"
	"tickets-hunter/app/usercenter/cmd/rpc/internal/svc"
	"tickets-hunter/app/usercenter/cmd/rpc/usercenter/rpc"
)

type UserCenterServer struct {
	svcCtx *svc.ServiceContext
	rpc.UnimplementedUserCenterServer
}

func NewUserCenterServer(svcCtx *svc.ServiceContext) *UserCenterServer {
	return &UserCenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UserCenterServer) Register(ctx context.Context, in *rpc.RegisterReq) (*rpc.RegisterResp, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserCenterServer) Login(ctx context.Context, in *rpc.LoginReq) (*rpc.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserCenterServer) Detail(ctx context.Context, in *rpc.DetailReq) (*rpc.DetailResp, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
