// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package ticket_seat

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ticketSeatFieldNames          = builder.RawFieldNames(&TicketSeat{})
	ticketSeatRows                = strings.Join(ticketSeatFieldNames, ",")
	ticketSeatRowsExpectAutoSet   = strings.Join(stringx.Remove(ticketSeatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ticketSeatRowsWithPlaceHolder = strings.Join(stringx.Remove(ticketSeatFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ticketSeatModel interface {
		Insert(ctx context.Context, data *TicketSeat) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TicketSeat, error)
		FindOneByEventIdSectionRowNoSeatNo(ctx context.Context, eventId int64, section string, rowNo int64, seatNo int64) (*TicketSeat, error)
		Update(ctx context.Context, data *TicketSeat) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTicketSeatModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TicketSeat struct {
		Id         int64     `db:"id"`
		EventId    int64     `db:"event_id"`   // 所属场次ID
		SeatType   int64     `db:"seat_type"`  // 座位类型: 1普通, 2VIP, 3内场
		Section    string    `db:"section"`    // 区域(如A区)
		SeatIndex  int64     `db:"seat_index"` // 区域内相对索引(从0开始, 映射Redis BitMap)
		RowNo      int64     `db:"row_no"`     // 排号
		SeatNo     int64     `db:"seat_no"`    // 座位号
		Price      int64     `db:"price"`      // 座位价格，以分为单位
		Status     int64     `db:"status"`     // 状态: 0可选, 1锁定(未支付), 2已售(已出票)
		Version    int64     `db:"version"`    // 乐观锁版本号(防超卖核心)
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newTicketSeatModel(conn sqlx.SqlConn) *defaultTicketSeatModel {
	return &defaultTicketSeatModel{
		conn:  conn,
		table: "`ticket_seat`",
	}
}

func (m *defaultTicketSeatModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTicketSeatModel) FindOne(ctx context.Context, id int64) (*TicketSeat, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ticketSeatRows, m.table)
	var resp TicketSeat
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTicketSeatModel) FindOneByEventIdSectionRowNoSeatNo(ctx context.Context, eventId int64, section string, rowNo int64, seatNo int64) (*TicketSeat, error) {
	var resp TicketSeat
	query := fmt.Sprintf("select %s from %s where `event_id` = ? and `section` = ? and `row_no` = ? and `seat_no` = ? limit 1", ticketSeatRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, eventId, section, rowNo, seatNo)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTicketSeatModel) Insert(ctx context.Context, data *TicketSeat) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, ticketSeatRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.EventId, data.SeatType, data.Section, data.SeatIndex, data.RowNo, data.SeatNo, data.Price, data.Status, data.Version)
	return ret, err
}

func (m *defaultTicketSeatModel) Update(ctx context.Context, newData *TicketSeat) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ticketSeatRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.EventId, newData.SeatType, newData.Section, newData.SeatIndex, newData.RowNo, newData.SeatNo, newData.Price, newData.Status, newData.Version, newData.Id)
	return err
}

func (m *defaultTicketSeatModel) tableName() string {
	return m.table
}
