// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	EventId int64 `json:"event_id" validate:"required,min=1"`
	SeatId  int64 `json:"seat_id" validate:"required,min=1"`
}

type CreateOrderResp struct {
	OrderSn    string  `json:"order_sn"`
	Amount     float64 `json:"amount"`
	ExpireTime string  `json:"expire_time"` // 告诉前端什么时候过期，用于显示倒计时
}

type OrderDetailReq struct {
	OrderSn string `form:"order_sn" validate:"required,min=1"`
}

type OrderDetailResp struct {
	OrderSn    string  `json:"order_sn"`
	EventId    int64   `json:"event_id"`
	SeatId     int64   `json:"seat_id"`
	Amount     float64 `json:"amount"`
	Status     int64   `json:"status"` // 0待支付, 1已支付, 2超时取消, 3已出票
	ExpireTime string  `json:"expire_time"`
	CreateTime string  `json:"create_time"`
}
