// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateOrderReq struct {
	EventId int64 `json:"event_id,optional" validate:"required,min=1"`
	SeatId  int64 `json:"seat_id,optional" validate:"required,min=1"`
}

type CreateOrderResp struct {
	OrderSn    string  `json:"order_sn"`
	Amount     float64 `json:"amount"`
	ExpireTime string  `json:"expire_time"` // 告诉前端什么时候过期，用于显示倒计时
}

type OrderDetailReq struct {
	OrderSn string `form:"order_sn,optional" validate:"required,min=1"`
}

type OrderDetailResp struct {
	OrderSn    string  `json:"order_sn"`
	EventId    int64   `json:"event_id"`
	SeatId     int64   `json:"seat_id"`
	Amount     float64 `json:"amount"`
	Status     int64   `json:"status"` // 订单状态: 10待支付, 20已支付(待出票), 30已出票(已完成)，40超时关闭，51已退款
	ExpireTime string  `json:"expire_time"`
	CreateTime string  `json:"create_time"`
}
