// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type EventInfo struct {
	Id            int64  `json:"id"`
	Title         string `json:"title"`
	CoverUrl      string `json:"cover_url"`
	ShowTime      string `json:"show_time"`
	Venue         string `json:"venue"`
	SaleStartTime string `json:"sale_start_time"`
	SaleEndTime   string `json:"sale_end_time"`
	Status        int64  `json:"status"`
}

type EventListResp struct {
	List  []EventInfo `json:"list"`
	Total int64       `json:"total"`
}

type SeatBitMapReq struct {
	EventId int64  `form:"event_id,optional" validate:"required,min=1"`
	Section string `form:"section" validate:"required,min=1"`
}

type SeatBitMapResp struct {
	Layout string `json:"layout"` // 座位图布局信息，例如行数、列数等
	BitMap string `json:"bitmap"` // 使用字符串表示座位状态的BitMap
}

type SeatInfo struct {
	Id       int64   `json:"id"`
	SeatType int64   `json:"seat_type"` // 1普通 2VIP 3内场
	Section  string  `json:"section"`
	RowNo    int64   `json:"row_no"`
	SeatNo   int64   `json:"seat_no"`
	Price    float64 `json:"price"`
	Status   int64   `json:"status"` // 0可选, 1锁定, 2已售
}

type SeatListReq struct {
	EventId int64 `form:"event_id,optional" validate:"required,min=1"`
}

type SeatListResp struct {
	List []SeatInfo `json:"list"`
}
