// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ticket.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EventInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EventInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EventInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EventInfoMultiError, or nil
// if none found.
func (m *EventInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *EventInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for CoverUrl

	// no validation rules for ShowTime

	// no validation rules for Venue

	// no validation rules for SaleStartTime

	// no validation rules for SaleEndTime

	// no validation rules for Status

	if len(errors) > 0 {
		return EventInfoMultiError(errors)
	}

	return nil
}

// EventInfoMultiError is an error wrapping multiple validation errors returned
// by EventInfo.ValidateAll() if the designated constraints aren't met.
type EventInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EventInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EventInfoMultiError) AllErrors() []error { return m }

// EventInfoValidationError is the validation error returned by
// EventInfo.Validate if the designated constraints aren't met.
type EventInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EventInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EventInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EventInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EventInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EventInfoValidationError) ErrorName() string { return "EventInfoValidationError" }

// Error satisfies the builtin error interface
func (e EventInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEventInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EventInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EventInfoValidationError{}

// Validate checks the field values on SeatInfo with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SeatInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SeatInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SeatInfoMultiError, or nil
// if none found.
func (m *SeatInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SeatInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SeatType

	// no validation rules for Section

	// no validation rules for RowNo

	// no validation rules for SeatNo

	// no validation rules for Price

	// no validation rules for Status

	// no validation rules for SeatIndex

	if len(errors) > 0 {
		return SeatInfoMultiError(errors)
	}

	return nil
}

// SeatInfoMultiError is an error wrapping multiple validation errors returned
// by SeatInfo.ValidateAll() if the designated constraints aren't met.
type SeatInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SeatInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SeatInfoMultiError) AllErrors() []error { return m }

// SeatInfoValidationError is the validation error returned by
// SeatInfo.Validate if the designated constraints aren't met.
type SeatInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SeatInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SeatInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SeatInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SeatInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SeatInfoValidationError) ErrorName() string { return "SeatInfoValidationError" }

// Error satisfies the builtin error interface
func (e SeatInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSeatInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SeatInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SeatInfoValidationError{}

// Validate checks the field values on GetEventListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEventListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventListReqMultiError, or nil if none found.
func (m *GetEventListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetEventListReqMultiError(errors)
	}

	return nil
}

// GetEventListReqMultiError is an error wrapping multiple validation errors
// returned by GetEventListReq.ValidateAll() if the designated constraints
// aren't met.
type GetEventListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventListReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventListReqMultiError) AllErrors() []error { return m }

// GetEventListReqValidationError is the validation error returned by
// GetEventListReq.Validate if the designated constraints aren't met.
type GetEventListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventListReqValidationError) ErrorName() string { return "GetEventListReqValidationError" }

// Error satisfies the builtin error interface
func (e GetEventListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventListReqValidationError{}

// Validate checks the field values on GetEventListResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetEventListResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEventListResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEventListRespMultiError, or nil if none found.
func (m *GetEventListResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEventListResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetEventListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetEventListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetEventListRespValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return GetEventListRespMultiError(errors)
	}

	return nil
}

// GetEventListRespMultiError is an error wrapping multiple validation errors
// returned by GetEventListResp.ValidateAll() if the designated constraints
// aren't met.
type GetEventListRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEventListRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEventListRespMultiError) AllErrors() []error { return m }

// GetEventListRespValidationError is the validation error returned by
// GetEventListResp.Validate if the designated constraints aren't met.
type GetEventListRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEventListRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEventListRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEventListRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEventListRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEventListRespValidationError) ErrorName() string { return "GetEventListRespValidationError" }

// Error satisfies the builtin error interface
func (e GetEventListRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEventListResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEventListRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEventListRespValidationError{}

// Validate checks the field values on GetSeatListReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetSeatListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeatListReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetSeatListReqMultiError,
// or nil if none found.
func (m *GetSeatListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeatListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := GetSeatListReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSeatListReqMultiError(errors)
	}

	return nil
}

// GetSeatListReqMultiError is an error wrapping multiple validation errors
// returned by GetSeatListReq.ValidateAll() if the designated constraints
// aren't met.
type GetSeatListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeatListReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeatListReqMultiError) AllErrors() []error { return m }

// GetSeatListReqValidationError is the validation error returned by
// GetSeatListReq.Validate if the designated constraints aren't met.
type GetSeatListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeatListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeatListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeatListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeatListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeatListReqValidationError) ErrorName() string { return "GetSeatListReqValidationError" }

// Error satisfies the builtin error interface
func (e GetSeatListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeatListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeatListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeatListReqValidationError{}

// Validate checks the field values on GetSeatListResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSeatListResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeatListResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSeatListRespMultiError, or nil if none found.
func (m *GetSeatListResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeatListResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetSeatListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetSeatListRespValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetSeatListRespValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetSeatListRespMultiError(errors)
	}

	return nil
}

// GetSeatListRespMultiError is an error wrapping multiple validation errors
// returned by GetSeatListResp.ValidateAll() if the designated constraints
// aren't met.
type GetSeatListRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeatListRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeatListRespMultiError) AllErrors() []error { return m }

// GetSeatListRespValidationError is the validation error returned by
// GetSeatListResp.Validate if the designated constraints aren't met.
type GetSeatListRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeatListRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeatListRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeatListRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeatListRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeatListRespValidationError) ErrorName() string { return "GetSeatListRespValidationError" }

// Error satisfies the builtin error interface
func (e GetSeatListRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeatListResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeatListRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeatListRespValidationError{}

// Validate checks the field values on LockSeatReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LockSeatReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LockSeatReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LockSeatReqMultiError, or
// nil if none found.
func (m *LockSeatReq) ValidateAll() error {
	return m.validate(true)
}

func (m *LockSeatReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := LockSeatReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSeatId() <= 0 {
		err := LockSeatReqValidationError{
			field:  "SeatId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrderSn()) < 1 {
		err := LockSeatReqValidationError{
			field:  "OrderSn",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSeatIndex() < 0 {
		err := LockSeatReqValidationError{
			field:  "SeatIndex",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSection()) < 1 {
		err := LockSeatReqValidationError{
			field:  "Section",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LockSeatReqMultiError(errors)
	}

	return nil
}

// LockSeatReqMultiError is an error wrapping multiple validation errors
// returned by LockSeatReq.ValidateAll() if the designated constraints aren't met.
type LockSeatReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LockSeatReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LockSeatReqMultiError) AllErrors() []error { return m }

// LockSeatReqValidationError is the validation error returned by
// LockSeatReq.Validate if the designated constraints aren't met.
type LockSeatReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LockSeatReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LockSeatReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LockSeatReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LockSeatReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LockSeatReqValidationError) ErrorName() string { return "LockSeatReqValidationError" }

// Error satisfies the builtin error interface
func (e LockSeatReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLockSeatReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LockSeatReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LockSeatReqValidationError{}

// Validate checks the field values on LockSeatResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LockSeatResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LockSeatResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LockSeatRespMultiError, or
// nil if none found.
func (m *LockSeatResp) ValidateAll() error {
	return m.validate(true)
}

func (m *LockSeatResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return LockSeatRespMultiError(errors)
	}

	return nil
}

// LockSeatRespMultiError is an error wrapping multiple validation errors
// returned by LockSeatResp.ValidateAll() if the designated constraints aren't met.
type LockSeatRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LockSeatRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LockSeatRespMultiError) AllErrors() []error { return m }

// LockSeatRespValidationError is the validation error returned by
// LockSeatResp.Validate if the designated constraints aren't met.
type LockSeatRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LockSeatRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LockSeatRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LockSeatRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LockSeatRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LockSeatRespValidationError) ErrorName() string { return "LockSeatRespValidationError" }

// Error satisfies the builtin error interface
func (e LockSeatRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLockSeatResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LockSeatRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LockSeatRespValidationError{}

// Validate checks the field values on GetSeatInfoReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetSeatInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeatInfoReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetSeatInfoReqMultiError,
// or nil if none found.
func (m *GetSeatInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeatInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSeatId() <= 0 {
		err := GetSeatInfoReqValidationError{
			field:  "SeatId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSeatInfoReqMultiError(errors)
	}

	return nil
}

// GetSeatInfoReqMultiError is an error wrapping multiple validation errors
// returned by GetSeatInfoReq.ValidateAll() if the designated constraints
// aren't met.
type GetSeatInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeatInfoReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeatInfoReqMultiError) AllErrors() []error { return m }

// GetSeatInfoReqValidationError is the validation error returned by
// GetSeatInfoReq.Validate if the designated constraints aren't met.
type GetSeatInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeatInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeatInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeatInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeatInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeatInfoReqValidationError) ErrorName() string { return "GetSeatInfoReqValidationError" }

// Error satisfies the builtin error interface
func (e GetSeatInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeatInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeatInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeatInfoReqValidationError{}

// Validate checks the field values on WarmUpValidSeatsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WarmUpValidSeatsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WarmUpValidSeatsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WarmUpValidSeatsReqMultiError, or nil if none found.
func (m *WarmUpValidSeatsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *WarmUpValidSeatsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := WarmUpValidSeatsReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return WarmUpValidSeatsReqMultiError(errors)
	}

	return nil
}

// WarmUpValidSeatsReqMultiError is an error wrapping multiple validation
// errors returned by WarmUpValidSeatsReq.ValidateAll() if the designated
// constraints aren't met.
type WarmUpValidSeatsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WarmUpValidSeatsReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WarmUpValidSeatsReqMultiError) AllErrors() []error { return m }

// WarmUpValidSeatsReqValidationError is the validation error returned by
// WarmUpValidSeatsReq.Validate if the designated constraints aren't met.
type WarmUpValidSeatsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WarmUpValidSeatsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WarmUpValidSeatsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WarmUpValidSeatsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WarmUpValidSeatsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WarmUpValidSeatsReqValidationError) ErrorName() string {
	return "WarmUpValidSeatsReqValidationError"
}

// Error satisfies the builtin error interface
func (e WarmUpValidSeatsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWarmUpValidSeatsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WarmUpValidSeatsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WarmUpValidSeatsReqValidationError{}

// Validate checks the field values on WarmUpValidSeatsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WarmUpValidSeatsResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WarmUpValidSeatsResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WarmUpValidSeatsRespMultiError, or nil if none found.
func (m *WarmUpValidSeatsResp) ValidateAll() error {
	return m.validate(true)
}

func (m *WarmUpValidSeatsResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return WarmUpValidSeatsRespMultiError(errors)
	}

	return nil
}

// WarmUpValidSeatsRespMultiError is an error wrapping multiple validation
// errors returned by WarmUpValidSeatsResp.ValidateAll() if the designated
// constraints aren't met.
type WarmUpValidSeatsRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WarmUpValidSeatsRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WarmUpValidSeatsRespMultiError) AllErrors() []error { return m }

// WarmUpValidSeatsRespValidationError is the validation error returned by
// WarmUpValidSeatsResp.Validate if the designated constraints aren't met.
type WarmUpValidSeatsRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WarmUpValidSeatsRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WarmUpValidSeatsRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WarmUpValidSeatsRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WarmUpValidSeatsRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WarmUpValidSeatsRespValidationError) ErrorName() string {
	return "WarmUpValidSeatsRespValidationError"
}

// Error satisfies the builtin error interface
func (e WarmUpValidSeatsRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWarmUpValidSeatsResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WarmUpValidSeatsRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WarmUpValidSeatsRespValidationError{}

// Validate checks the field values on UnlockSeatReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UnlockSeatReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnlockSeatReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UnlockSeatReqMultiError, or
// nil if none found.
func (m *UnlockSeatReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UnlockSeatReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSeatId() <= 0 {
		err := UnlockSeatReqValidationError{
			field:  "SeatId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrderSn()) < 1 {
		err := UnlockSeatReqValidationError{
			field:  "OrderSn",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSeatIndex() < 0 {
		err := UnlockSeatReqValidationError{
			field:  "SeatIndex",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSection()) < 1 {
		err := UnlockSeatReqValidationError{
			field:  "Section",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetEventId() <= 0 {
		err := UnlockSeatReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UnlockSeatReqMultiError(errors)
	}

	return nil
}

// UnlockSeatReqMultiError is an error wrapping multiple validation errors
// returned by UnlockSeatReq.ValidateAll() if the designated constraints
// aren't met.
type UnlockSeatReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnlockSeatReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnlockSeatReqMultiError) AllErrors() []error { return m }

// UnlockSeatReqValidationError is the validation error returned by
// UnlockSeatReq.Validate if the designated constraints aren't met.
type UnlockSeatReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnlockSeatReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnlockSeatReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnlockSeatReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnlockSeatReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnlockSeatReqValidationError) ErrorName() string { return "UnlockSeatReqValidationError" }

// Error satisfies the builtin error interface
func (e UnlockSeatReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnlockSeatReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnlockSeatReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnlockSeatReqValidationError{}

// Validate checks the field values on UnlockSeatResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UnlockSeatResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnlockSeatResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UnlockSeatRespMultiError,
// or nil if none found.
func (m *UnlockSeatResp) ValidateAll() error {
	return m.validate(true)
}

func (m *UnlockSeatResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return UnlockSeatRespMultiError(errors)
	}

	return nil
}

// UnlockSeatRespMultiError is an error wrapping multiple validation errors
// returned by UnlockSeatResp.ValidateAll() if the designated constraints
// aren't met.
type UnlockSeatRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnlockSeatRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnlockSeatRespMultiError) AllErrors() []error { return m }

// UnlockSeatRespValidationError is the validation error returned by
// UnlockSeatResp.Validate if the designated constraints aren't met.
type UnlockSeatRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnlockSeatRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnlockSeatRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnlockSeatRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnlockSeatRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnlockSeatRespValidationError) ErrorName() string { return "UnlockSeatRespValidationError" }

// Error satisfies the builtin error interface
func (e UnlockSeatRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnlockSeatResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnlockSeatRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnlockSeatRespValidationError{}

// Validate checks the field values on ReleaseSeatReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReleaseSeatReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseSeatReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReleaseSeatReqMultiError,
// or nil if none found.
func (m *ReleaseSeatReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseSeatReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetSeatId() <= 0 {
		err := ReleaseSeatReqValidationError{
			field:  "SeatId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetOrderSn()) < 1 {
		err := ReleaseSeatReqValidationError{
			field:  "OrderSn",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetSeatIndex() < 0 {
		err := ReleaseSeatReqValidationError{
			field:  "SeatIndex",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSection()) < 1 {
		err := ReleaseSeatReqValidationError{
			field:  "Section",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetEventId() <= 0 {
		err := ReleaseSeatReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ReleaseSeatReqMultiError(errors)
	}

	return nil
}

// ReleaseSeatReqMultiError is an error wrapping multiple validation errors
// returned by ReleaseSeatReq.ValidateAll() if the designated constraints
// aren't met.
type ReleaseSeatReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseSeatReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseSeatReqMultiError) AllErrors() []error { return m }

// ReleaseSeatReqValidationError is the validation error returned by
// ReleaseSeatReq.Validate if the designated constraints aren't met.
type ReleaseSeatReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseSeatReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseSeatReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseSeatReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseSeatReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseSeatReqValidationError) ErrorName() string { return "ReleaseSeatReqValidationError" }

// Error satisfies the builtin error interface
func (e ReleaseSeatReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseSeatReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseSeatReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseSeatReqValidationError{}

// Validate checks the field values on ReleaseSeatResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ReleaseSeatResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReleaseSeatResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReleaseSeatRespMultiError, or nil if none found.
func (m *ReleaseSeatResp) ValidateAll() error {
	return m.validate(true)
}

func (m *ReleaseSeatResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return ReleaseSeatRespMultiError(errors)
	}

	return nil
}

// ReleaseSeatRespMultiError is an error wrapping multiple validation errors
// returned by ReleaseSeatResp.ValidateAll() if the designated constraints
// aren't met.
type ReleaseSeatRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReleaseSeatRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReleaseSeatRespMultiError) AllErrors() []error { return m }

// ReleaseSeatRespValidationError is the validation error returned by
// ReleaseSeatResp.Validate if the designated constraints aren't met.
type ReleaseSeatRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReleaseSeatRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReleaseSeatRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReleaseSeatRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReleaseSeatRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReleaseSeatRespValidationError) ErrorName() string { return "ReleaseSeatRespValidationError" }

// Error satisfies the builtin error interface
func (e ReleaseSeatRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReleaseSeatResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReleaseSeatRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReleaseSeatRespValidationError{}

// Validate checks the field values on GetSeatBitMapReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSeatBitMapReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeatBitMapReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSeatBitMapReqMultiError, or nil if none found.
func (m *GetSeatBitMapReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeatBitMapReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetEventId() <= 0 {
		err := GetSeatBitMapReqValidationError{
			field:  "EventId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSection()) < 1 {
		err := GetSeatBitMapReqValidationError{
			field:  "Section",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetSeatBitMapReqMultiError(errors)
	}

	return nil
}

// GetSeatBitMapReqMultiError is an error wrapping multiple validation errors
// returned by GetSeatBitMapReq.ValidateAll() if the designated constraints
// aren't met.
type GetSeatBitMapReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeatBitMapReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeatBitMapReqMultiError) AllErrors() []error { return m }

// GetSeatBitMapReqValidationError is the validation error returned by
// GetSeatBitMapReq.Validate if the designated constraints aren't met.
type GetSeatBitMapReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeatBitMapReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeatBitMapReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeatBitMapReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeatBitMapReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeatBitMapReqValidationError) ErrorName() string { return "GetSeatBitMapReqValidationError" }

// Error satisfies the builtin error interface
func (e GetSeatBitMapReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeatBitMapReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeatBitMapReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeatBitMapReqValidationError{}

// Validate checks the field values on GetSeatBitMapResp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSeatBitMapResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSeatBitMapResp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSeatBitMapRespMultiError, or nil if none found.
func (m *GetSeatBitMapResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSeatBitMapResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Bitmap

	if len(errors) > 0 {
		return GetSeatBitMapRespMultiError(errors)
	}

	return nil
}

// GetSeatBitMapRespMultiError is an error wrapping multiple validation errors
// returned by GetSeatBitMapResp.ValidateAll() if the designated constraints
// aren't met.
type GetSeatBitMapRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSeatBitMapRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSeatBitMapRespMultiError) AllErrors() []error { return m }

// GetSeatBitMapRespValidationError is the validation error returned by
// GetSeatBitMapResp.Validate if the designated constraints aren't met.
type GetSeatBitMapRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSeatBitMapRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSeatBitMapRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSeatBitMapRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSeatBitMapRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSeatBitMapRespValidationError) ErrorName() string {
	return "GetSeatBitMapRespValidationError"
}

// Error satisfies the builtin error interface
func (e GetSeatBitMapRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSeatBitMapResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSeatBitMapRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSeatBitMapRespValidationError{}
