// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: ticket.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 演唱会场次信息
type EventInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	ShowTime      string                 `protobuf:"bytes,4,opt,name=show_time,json=showTime,proto3" json:"show_time,omitempty"`
	Venue         string                 `protobuf:"bytes,5,opt,name=venue,proto3" json:"venue,omitempty"`
	SaleStartTime string                 `protobuf:"bytes,6,opt,name=sale_start_time,json=saleStartTime,proto3" json:"sale_start_time,omitempty"`
	SaleEndTime   string                 `protobuf:"bytes,7,opt,name=sale_end_time,json=saleEndTime,proto3" json:"sale_end_time,omitempty"`
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventInfo) Reset() {
	*x = EventInfo{}
	mi := &file_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventInfo) ProtoMessage() {}

func (x *EventInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventInfo.ProtoReflect.Descriptor instead.
func (*EventInfo) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *EventInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EventInfo) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *EventInfo) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *EventInfo) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *EventInfo) GetSaleStartTime() string {
	if x != nil {
		return x.SaleStartTime
	}
	return ""
}

func (x *EventInfo) GetSaleEndTime() string {
	if x != nil {
		return x.SaleEndTime
	}
	return ""
}

func (x *EventInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 座位信息
type SeatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SeatType      int64                  `protobuf:"varint,2,opt,name=seat_type,json=seatType,proto3" json:"seat_type,omitempty"`    // 座位类型: 1普通 2VIP 3内场
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`                       // 区域
	RowNo         int64                  `protobuf:"varint,4,opt,name=row_no,json=rowNo,proto3" json:"row_no,omitempty"`             // 排号
	SeatNo        int64                  `protobuf:"varint,5,opt,name=seat_no,json=seatNo,proto3" json:"seat_no,omitempty"`          // 座位号
	Price         int64                  `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`                          // 价格 (用int64分来表示金额)
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                        // 状态: 0可选, 1锁定(未支付), 2已售(已出票)
	SeatIndex     int64                  `protobuf:"varint,8,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"` // 同一个区域内的座位索引
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatInfo) Reset() {
	*x = SeatInfo{}
	mi := &file_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatInfo) ProtoMessage() {}

func (x *SeatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatInfo.ProtoReflect.Descriptor instead.
func (*SeatInfo) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *SeatInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SeatInfo) GetSeatType() int64 {
	if x != nil {
		return x.SeatType
	}
	return 0
}

func (x *SeatInfo) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SeatInfo) GetRowNo() int64 {
	if x != nil {
		return x.RowNo
	}
	return 0
}

func (x *SeatInfo) GetSeatNo() int64 {
	if x != nil {
		return x.SeatNo
	}
	return 0
}

func (x *SeatInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SeatInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SeatInfo) GetSeatIndex() int64 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

// 2.1 获取场次列表
type GetEventListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListReq) Reset() {
	*x = GetEventListReq{}
	mi := &file_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListReq) ProtoMessage() {}

func (x *GetEventListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListReq.ProtoReflect.Descriptor instead.
func (*GetEventListReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{2}
}

type GetEventListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*EventInfo           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventListResp) Reset() {
	*x = GetEventListResp{}
	mi := &file_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventListResp) ProtoMessage() {}

func (x *GetEventListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventListResp.ProtoReflect.Descriptor instead.
func (*GetEventListResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventListResp) GetList() []*EventInfo {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetEventListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 2.2 获取座位列表
type GetSeatListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 场次ID，必填且必须大于0
	EventId       int64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatListReq) Reset() {
	*x = GetSeatListReq{}
	mi := &file_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatListReq) ProtoMessage() {}

func (x *GetSeatListReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatListReq.ProtoReflect.Descriptor instead.
func (*GetSeatListReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *GetSeatListReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type GetSeatListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SeatInfo            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatListResp) Reset() {
	*x = GetSeatListResp{}
	mi := &file_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatListResp) ProtoMessage() {}

func (x *GetSeatListResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatListResp.ProtoReflect.Descriptor instead.
func (*GetSeatListResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *GetSeatListResp) GetList() []*SeatInfo {
	if x != nil {
		return x.List
	}
	return nil
}

// 2.3 锁定座位 (防超卖核心)
type LockSeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SeatId        int64                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`        // 订单号，用于锁定座位
	SeatIndex     int64                  `protobuf:"varint,4,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"` // 使用BitMap进行的优化
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatReq) Reset() {
	*x = LockSeatReq{}
	mi := &file_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatReq) ProtoMessage() {}

func (x *LockSeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatReq.ProtoReflect.Descriptor instead.
func (*LockSeatReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *LockSeatReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *LockSeatReq) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *LockSeatReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *LockSeatReq) GetSeatIndex() int64 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *LockSeatReq) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type LockSeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否锁座成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockSeatResp) Reset() {
	*x = LockSeatResp{}
	mi := &file_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockSeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockSeatResp) ProtoMessage() {}

func (x *LockSeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockSeatResp.ProtoReflect.Descriptor instead.
func (*LockSeatResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *LockSeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 2.4 获取座位信息 (供 Order RPC 内部调用)
type GetSeatInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int64                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatInfoReq) Reset() {
	*x = GetSeatInfoReq{}
	mi := &file_ticket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatInfoReq) ProtoMessage() {}

func (x *GetSeatInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatInfoReq.ProtoReflect.Descriptor instead.
func (*GetSeatInfoReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{8}
}

func (x *GetSeatInfoReq) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

// 2.5 有效座位集合缓存预热
type WarmUpValidSeatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmUpValidSeatsReq) Reset() {
	*x = WarmUpValidSeatsReq{}
	mi := &file_ticket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmUpValidSeatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmUpValidSeatsReq) ProtoMessage() {}

func (x *WarmUpValidSeatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmUpValidSeatsReq.ProtoReflect.Descriptor instead.
func (*WarmUpValidSeatsReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{9}
}

func (x *WarmUpValidSeatsReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type WarmUpValidSeatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否预热成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmUpValidSeatsResp) Reset() {
	*x = WarmUpValidSeatsResp{}
	mi := &file_ticket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmUpValidSeatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmUpValidSeatsResp) ProtoMessage() {}

func (x *WarmUpValidSeatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmUpValidSeatsResp.ProtoReflect.Descriptor instead.
func (*WarmUpValidSeatsResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{10}
}

func (x *WarmUpValidSeatsResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 2.6 取消锁定座位 (供 Order RPC 内部调用)
type UnlockSeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int64                  `protobuf:"varint,2,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`        // 订单号，用于解锁座位
	SeatIndex     int64                  `protobuf:"varint,4,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"` // 使用BitMap进行的优化
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	EventId       int64                  `protobuf:"varint,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 场次Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockSeatReq) Reset() {
	*x = UnlockSeatReq{}
	mi := &file_ticket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockSeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockSeatReq) ProtoMessage() {}

func (x *UnlockSeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockSeatReq.ProtoReflect.Descriptor instead.
func (*UnlockSeatReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{11}
}

func (x *UnlockSeatReq) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *UnlockSeatReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UnlockSeatReq) GetSeatIndex() int64 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *UnlockSeatReq) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *UnlockSeatReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type UnlockSeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否解锁成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockSeatResp) Reset() {
	*x = UnlockSeatResp{}
	mi := &file_ticket_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockSeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockSeatResp) ProtoMessage() {}

func (x *UnlockSeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockSeatResp.ProtoReflect.Descriptor instead.
func (*UnlockSeatResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{12}
}

func (x *UnlockSeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 2.7 释放座位
type ReleaseSeatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        int64                  `protobuf:"varint,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`        // 订单号，用于释放座位
	SeatIndex     int64                  `protobuf:"varint,4,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"` // 使用BitMap进行的优化
	Section       string                 `protobuf:"bytes,5,opt,name=section,proto3" json:"section,omitempty"`
	EventId       int64                  `protobuf:"varint,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 场次Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatReq) Reset() {
	*x = ReleaseSeatReq{}
	mi := &file_ticket_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatReq) ProtoMessage() {}

func (x *ReleaseSeatReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatReq.ProtoReflect.Descriptor instead.
func (*ReleaseSeatReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseSeatReq) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *ReleaseSeatReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ReleaseSeatReq) GetSeatIndex() int64 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *ReleaseSeatReq) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ReleaseSeatReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

type ReleaseSeatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否释放成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatResp) Reset() {
	*x = ReleaseSeatResp{}
	mi := &file_ticket_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatResp) ProtoMessage() {}

func (x *ReleaseSeatResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatResp.ProtoReflect.Descriptor instead.
func (*ReleaseSeatResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{14}
}

func (x *ReleaseSeatResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 2.8 获取指定区域的座位状态
type GetSeatBitMapReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 场次ID
	Section       string                 `protobuf:"bytes,2,opt,name=section,proto3" json:"section,omitempty"`                 // 区域信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatBitMapReq) Reset() {
	*x = GetSeatBitMapReq{}
	mi := &file_ticket_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatBitMapReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatBitMapReq) ProtoMessage() {}

func (x *GetSeatBitMapReq) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatBitMapReq.ProtoReflect.Descriptor instead.
func (*GetSeatBitMapReq) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{15}
}

func (x *GetSeatBitMapReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *GetSeatBitMapReq) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type GetSeatBitMapResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bitmap        []byte                 `protobuf:"bytes,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"` // bitmap信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatBitMapResp) Reset() {
	*x = GetSeatBitMapResp{}
	mi := &file_ticket_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatBitMapResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatBitMapResp) ProtoMessage() {}

func (x *GetSeatBitMapResp) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatBitMapResp.ProtoReflect.Descriptor instead.
func (*GetSeatBitMapResp) Descriptor() ([]byte, []int) {
	return file_ticket_proto_rawDescGZIP(), []int{16}
}

func (x *GetSeatBitMapResp) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

var File_ticket_proto protoreflect.FileDescriptor

const file_ticket_proto_rawDesc = "" +
	"\n" +
	"\fticket.proto\x12\x06ticket\x1a\x1avalidate/rpcvalidate.proto\"\xe5\x01\n" +
	"\tEventInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tshow_time\x18\x04 \x01(\tR\bshowTime\x12\x14\n" +
	"\x05venue\x18\x05 \x01(\tR\x05venue\x12&\n" +
	"\x0fsale_start_time\x18\x06 \x01(\tR\rsaleStartTime\x12\"\n" +
	"\rsale_end_time\x18\a \x01(\tR\vsaleEndTime\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\"\xce\x01\n" +
	"\bSeatInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tseat_type\x18\x02 \x01(\x03R\bseatType\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12\x15\n" +
	"\x06row_no\x18\x04 \x01(\x03R\x05rowNo\x12\x17\n" +
	"\aseat_no\x18\x05 \x01(\x03R\x06seatNo\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"seat_index\x18\b \x01(\x03R\tseatIndex\"\x11\n" +
	"\x0fGetEventListReq\"O\n" +
	"\x10GetEventListResp\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.ticket.EventInfoR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"4\n" +
	"\x0eGetSeatListReq\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\"7\n" +
	"\x0fGetSeatListResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.ticket.SeatInfoR\x04list\"\xc2\x01\n" +
	"\vLockSeatReq\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\x12 \n" +
	"\aseat_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06seatId\x12\"\n" +
	"\border_sn\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderSn\x12&\n" +
	"\n" +
	"seat_index\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\tseatIndex\x12!\n" +
	"\asection\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\asection\"(\n" +
	"\fLockSeatResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x0eGetSeatInfoReq\x12 \n" +
	"\aseat_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06seatId\"9\n" +
	"\x13WarmUpValidSeatsReq\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\"0\n" +
	"\x14WarmUpValidSeatsResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc4\x01\n" +
	"\rUnlockSeatReq\x12 \n" +
	"\aseat_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06seatId\x12\"\n" +
	"\border_sn\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderSn\x12&\n" +
	"\n" +
	"seat_index\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\tseatIndex\x12!\n" +
	"\asection\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\asection\x12\"\n" +
	"\bevent_id\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\"*\n" +
	"\x0eUnlockSeatResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc5\x01\n" +
	"\x0eReleaseSeatReq\x12 \n" +
	"\aseat_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06seatId\x12\"\n" +
	"\border_sn\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderSn\x12&\n" +
	"\n" +
	"seat_index\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\tseatIndex\x12!\n" +
	"\asection\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\asection\x12\"\n" +
	"\bevent_id\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\"+\n" +
	"\x0fReleaseSeatResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x10GetSeatBitMapReq\x12\"\n" +
	"\bevent_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aeventId\x12!\n" +
	"\asection\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\asection\"+\n" +
	"\x11GetSeatBitMapResp\x12\x16\n" +
	"\x06bitmap\x18\x01 \x01(\fR\x06bitmap2\x98\x05\n" +
	"\rTicketService\x12A\n" +
	"\fGetEventList\x12\x17.ticket.GetEventListReq\x1a\x18.ticket.GetEventListResp\x12>\n" +
	"\vGetSeatList\x12\x16.ticket.GetSeatListReq\x1a\x17.ticket.GetSeatListResp\x125\n" +
	"\bLockSeat\x12\x13.ticket.LockSeatReq\x1a\x14.ticket.LockSeatResp\x128\n" +
	"\vAcquireSeat\x12\x13.ticket.LockSeatReq\x1a\x14.ticket.LockSeatResp\x127\n" +
	"\vGetSeatInfo\x12\x16.ticket.GetSeatInfoReq\x1a\x10.ticket.SeatInfo\x12M\n" +
	"\x10WarmUpValidSeats\x12\x1b.ticket.WarmUpValidSeatsReq\x1a\x1c.ticket.WarmUpValidSeatsResp\x12;\n" +
	"\n" +
	"UnlockSeat\x12\x15.ticket.UnlockSeatReq\x1a\x16.ticket.UnlockSeatResp\x12>\n" +
	"\vReleaseSeat\x12\x16.ticket.ReleaseSeatReq\x1a\x17.ticket.ReleaseSeatResp\x12H\n" +
	"\x15UnderwriteReleaseSeat\x12\x16.ticket.ReleaseSeatReq\x1a\x17.ticket.ReleaseSeatResp\x12D\n" +
	"\rGetSeatBitMap\x12\x18.ticket.GetSeatBitMapReq\x1a\x19.ticket.GetSeatBitMapRespB\fZ\n" +
	"ticket/rpcb\x06proto3"

var (
	file_ticket_proto_rawDescOnce sync.Once
	file_ticket_proto_rawDescData []byte
)

func file_ticket_proto_rawDescGZIP() []byte {
	file_ticket_proto_rawDescOnce.Do(func() {
		file_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ticket_proto_rawDesc), len(file_ticket_proto_rawDesc)))
	})
	return file_ticket_proto_rawDescData
}

var file_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ticket_proto_goTypes = []any{
	(*EventInfo)(nil),            // 0: ticket.EventInfo
	(*SeatInfo)(nil),             // 1: ticket.SeatInfo
	(*GetEventListReq)(nil),      // 2: ticket.GetEventListReq
	(*GetEventListResp)(nil),     // 3: ticket.GetEventListResp
	(*GetSeatListReq)(nil),       // 4: ticket.GetSeatListReq
	(*GetSeatListResp)(nil),      // 5: ticket.GetSeatListResp
	(*LockSeatReq)(nil),          // 6: ticket.LockSeatReq
	(*LockSeatResp)(nil),         // 7: ticket.LockSeatResp
	(*GetSeatInfoReq)(nil),       // 8: ticket.GetSeatInfoReq
	(*WarmUpValidSeatsReq)(nil),  // 9: ticket.WarmUpValidSeatsReq
	(*WarmUpValidSeatsResp)(nil), // 10: ticket.WarmUpValidSeatsResp
	(*UnlockSeatReq)(nil),        // 11: ticket.UnlockSeatReq
	(*UnlockSeatResp)(nil),       // 12: ticket.UnlockSeatResp
	(*ReleaseSeatReq)(nil),       // 13: ticket.ReleaseSeatReq
	(*ReleaseSeatResp)(nil),      // 14: ticket.ReleaseSeatResp
	(*GetSeatBitMapReq)(nil),     // 15: ticket.GetSeatBitMapReq
	(*GetSeatBitMapResp)(nil),    // 16: ticket.GetSeatBitMapResp
}
var file_ticket_proto_depIdxs = []int32{
	0,  // 0: ticket.GetEventListResp.list:type_name -> ticket.EventInfo
	1,  // 1: ticket.GetSeatListResp.list:type_name -> ticket.SeatInfo
	2,  // 2: ticket.TicketService.GetEventList:input_type -> ticket.GetEventListReq
	4,  // 3: ticket.TicketService.GetSeatList:input_type -> ticket.GetSeatListReq
	6,  // 4: ticket.TicketService.LockSeat:input_type -> ticket.LockSeatReq
	6,  // 5: ticket.TicketService.AcquireSeat:input_type -> ticket.LockSeatReq
	8,  // 6: ticket.TicketService.GetSeatInfo:input_type -> ticket.GetSeatInfoReq
	9,  // 7: ticket.TicketService.WarmUpValidSeats:input_type -> ticket.WarmUpValidSeatsReq
	11, // 8: ticket.TicketService.UnlockSeat:input_type -> ticket.UnlockSeatReq
	13, // 9: ticket.TicketService.ReleaseSeat:input_type -> ticket.ReleaseSeatReq
	13, // 10: ticket.TicketService.UnderwriteReleaseSeat:input_type -> ticket.ReleaseSeatReq
	15, // 11: ticket.TicketService.GetSeatBitMap:input_type -> ticket.GetSeatBitMapReq
	3,  // 12: ticket.TicketService.GetEventList:output_type -> ticket.GetEventListResp
	5,  // 13: ticket.TicketService.GetSeatList:output_type -> ticket.GetSeatListResp
	7,  // 14: ticket.TicketService.LockSeat:output_type -> ticket.LockSeatResp
	7,  // 15: ticket.TicketService.AcquireSeat:output_type -> ticket.LockSeatResp
	1,  // 16: ticket.TicketService.GetSeatInfo:output_type -> ticket.SeatInfo
	10, // 17: ticket.TicketService.WarmUpValidSeats:output_type -> ticket.WarmUpValidSeatsResp
	12, // 18: ticket.TicketService.UnlockSeat:output_type -> ticket.UnlockSeatResp
	14, // 19: ticket.TicketService.ReleaseSeat:output_type -> ticket.ReleaseSeatResp
	14, // 20: ticket.TicketService.UnderwriteReleaseSeat:output_type -> ticket.ReleaseSeatResp
	16, // 21: ticket.TicketService.GetSeatBitMap:output_type -> ticket.GetSeatBitMapResp
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ticket_proto_init() }
func file_ticket_proto_init() {
	if File_ticket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ticket_proto_rawDesc), len(file_ticket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_proto_goTypes,
		DependencyIndexes: file_ticket_proto_depIdxs,
		MessageInfos:      file_ticket_proto_msgTypes,
	}.Build()
	File_ticket_proto = out.File
	file_ticket_proto_goTypes = nil
	file_ticket_proto_depIdxs = nil
}
