// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: ticket.proto

package rpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TicketService_GetEventList_FullMethodName     = "/ticket.TicketService/GetEventList"
	TicketService_GetSeatList_FullMethodName      = "/ticket.TicketService/GetSeatList"
	TicketService_LockSeat_FullMethodName         = "/ticket.TicketService/LockSeat"
	TicketService_GetSeatInfo_FullMethodName      = "/ticket.TicketService/GetSeatInfo"
	TicketService_WarmUpValidSeats_FullMethodName = "/ticket.TicketService/WarmUpValidSeats"
	TicketService_UnlockSeat_FullMethodName       = "/ticket.TicketService/UnlockSeat"
	TicketService_ReleaseSeat_FullMethodName      = "/ticket.TicketService/ReleaseSeat"
	TicketService_GetSeatBitMap_FullMethodName    = "/ticket.TicketService/GetSeatBitMap"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketServiceClient interface {
	// 获取演唱会场次列表 (供 API 层调用)
	GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error)
	// 获取指定场次的座位图及状态 (供 API 层调用)
	GetSeatList(ctx context.Context, in *GetSeatListReq, opts ...grpc.CallOption) (*GetSeatListResp, error)
	// 锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
	LockSeat(ctx context.Context, in *LockSeatReq, opts ...grpc.CallOption) (*LockSeatResp, error)
	// 获取座位信息 (供 Order RPC 内部调用)
	GetSeatInfo(ctx context.Context, in *GetSeatInfoReq, opts ...grpc.CallOption) (*SeatInfo, error)
	// 有效座位集合缓存预热 (内部隐藏接口，实际场景中可能由定时任务调用)
	WarmUpValidSeats(ctx context.Context, in *WarmUpValidSeatsReq, opts ...grpc.CallOption) (*WarmUpValidSeatsResp, error)
	// 取消锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
	UnlockSeat(ctx context.Context, in *UnlockSeatReq, opts ...grpc.CallOption) (*UnlockSeatResp, error)
	// 释放座位，供订单支付超时或用户取消订单时调用，更新MySQL的座位状态为可选，并删除Redis中的锁定状态
	ReleaseSeat(ctx context.Context, in *ReleaseSeatReq, opts ...grpc.CallOption) (*ReleaseSeatResp, error)
	// 获取BitMap信息
	GetSeatBitMap(ctx context.Context, in *GetSeatBitMapReq, opts ...grpc.CallOption) (*GetEventListResp, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventListResp)
	err := c.cc.Invoke(ctx, TicketService_GetEventList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetSeatList(ctx context.Context, in *GetSeatListReq, opts ...grpc.CallOption) (*GetSeatListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeatListResp)
	err := c.cc.Invoke(ctx, TicketService_GetSeatList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) LockSeat(ctx context.Context, in *LockSeatReq, opts ...grpc.CallOption) (*LockSeatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockSeatResp)
	err := c.cc.Invoke(ctx, TicketService_LockSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetSeatInfo(ctx context.Context, in *GetSeatInfoReq, opts ...grpc.CallOption) (*SeatInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatInfo)
	err := c.cc.Invoke(ctx, TicketService_GetSeatInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) WarmUpValidSeats(ctx context.Context, in *WarmUpValidSeatsReq, opts ...grpc.CallOption) (*WarmUpValidSeatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WarmUpValidSeatsResp)
	err := c.cc.Invoke(ctx, TicketService_WarmUpValidSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UnlockSeat(ctx context.Context, in *UnlockSeatReq, opts ...grpc.CallOption) (*UnlockSeatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockSeatResp)
	err := c.cc.Invoke(ctx, TicketService_UnlockSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ReleaseSeat(ctx context.Context, in *ReleaseSeatReq, opts ...grpc.CallOption) (*ReleaseSeatResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSeatResp)
	err := c.cc.Invoke(ctx, TicketService_ReleaseSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetSeatBitMap(ctx context.Context, in *GetSeatBitMapReq, opts ...grpc.CallOption) (*GetEventListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventListResp)
	err := c.cc.Invoke(ctx, TicketService_GetSeatBitMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations must embed UnimplementedTicketServiceServer
// for forward compatibility.
type TicketServiceServer interface {
	// 获取演唱会场次列表 (供 API 层调用)
	GetEventList(context.Context, *GetEventListReq) (*GetEventListResp, error)
	// 获取指定场次的座位图及状态 (供 API 层调用)
	GetSeatList(context.Context, *GetSeatListReq) (*GetSeatListResp, error)
	// 锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
	LockSeat(context.Context, *LockSeatReq) (*LockSeatResp, error)
	// 获取座位信息 (供 Order RPC 内部调用)
	GetSeatInfo(context.Context, *GetSeatInfoReq) (*SeatInfo, error)
	// 有效座位集合缓存预热 (内部隐藏接口，实际场景中可能由定时任务调用)
	WarmUpValidSeats(context.Context, *WarmUpValidSeatsReq) (*WarmUpValidSeatsResp, error)
	// 取消锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
	UnlockSeat(context.Context, *UnlockSeatReq) (*UnlockSeatResp, error)
	// 释放座位，供订单支付超时或用户取消订单时调用，更新MySQL的座位状态为可选，并删除Redis中的锁定状态
	ReleaseSeat(context.Context, *ReleaseSeatReq) (*ReleaseSeatResp, error)
	// 获取BitMap信息
	GetSeatBitMap(context.Context, *GetSeatBitMapReq) (*GetEventListResp, error)
	mustEmbedUnimplementedTicketServiceServer()
}

// UnimplementedTicketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTicketServiceServer struct{}

func (UnimplementedTicketServiceServer) GetEventList(context.Context, *GetEventListReq) (*GetEventListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventList not implemented")
}
func (UnimplementedTicketServiceServer) GetSeatList(context.Context, *GetSeatListReq) (*GetSeatListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatList not implemented")
}
func (UnimplementedTicketServiceServer) LockSeat(context.Context, *LockSeatReq) (*LockSeatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LockSeat not implemented")
}
func (UnimplementedTicketServiceServer) GetSeatInfo(context.Context, *GetSeatInfoReq) (*SeatInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatInfo not implemented")
}
func (UnimplementedTicketServiceServer) WarmUpValidSeats(context.Context, *WarmUpValidSeatsReq) (*WarmUpValidSeatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method WarmUpValidSeats not implemented")
}
func (UnimplementedTicketServiceServer) UnlockSeat(context.Context, *UnlockSeatReq) (*UnlockSeatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockSeat not implemented")
}
func (UnimplementedTicketServiceServer) ReleaseSeat(context.Context, *ReleaseSeatReq) (*ReleaseSeatResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSeat not implemented")
}
func (UnimplementedTicketServiceServer) GetSeatBitMap(context.Context, *GetSeatBitMapReq) (*GetEventListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatBitMap not implemented")
}
func (UnimplementedTicketServiceServer) mustEmbedUnimplementedTicketServiceServer() {}
func (UnimplementedTicketServiceServer) testEmbeddedByValue()                       {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	// If the following call panics, it indicates UnimplementedTicketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_GetEventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetEventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetEventList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetEventList(ctx, req.(*GetEventListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetSeatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetSeatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetSeatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetSeatList(ctx, req.(*GetSeatListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_LockSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockSeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).LockSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_LockSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).LockSeat(ctx, req.(*LockSeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetSeatInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetSeatInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetSeatInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetSeatInfo(ctx, req.(*GetSeatInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_WarmUpValidSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarmUpValidSeatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).WarmUpValidSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_WarmUpValidSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).WarmUpValidSeats(ctx, req.(*WarmUpValidSeatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UnlockSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockSeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UnlockSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UnlockSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UnlockSeat(ctx, req.(*UnlockSeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ReleaseSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSeatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ReleaseSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ReleaseSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ReleaseSeat(ctx, req.(*ReleaseSeatReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetSeatBitMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatBitMapReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetSeatBitMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetSeatBitMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetSeatBitMap(ctx, req.(*GetSeatBitMapReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventList",
			Handler:    _TicketService_GetEventList_Handler,
		},
		{
			MethodName: "GetSeatList",
			Handler:    _TicketService_GetSeatList_Handler,
		},
		{
			MethodName: "LockSeat",
			Handler:    _TicketService_LockSeat_Handler,
		},
		{
			MethodName: "GetSeatInfo",
			Handler:    _TicketService_GetSeatInfo_Handler,
		},
		{
			MethodName: "WarmUpValidSeats",
			Handler:    _TicketService_WarmUpValidSeats_Handler,
		},
		{
			MethodName: "UnlockSeat",
			Handler:    _TicketService_UnlockSeat_Handler,
		},
		{
			MethodName: "ReleaseSeat",
			Handler:    _TicketService_ReleaseSeat_Handler,
		},
		{
			MethodName: "GetSeatBitMap",
			Handler:    _TicketService_GetSeatBitMap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket.proto",
}
