// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: payment.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SagaPayReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SagaPayReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SagaPayReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SagaPayReqMultiError, or
// nil if none found.
func (m *SagaPayReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SagaPayReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderSn

	// no validation rules for UserId

	// no validation rules for Amount

	// no validation rules for SeatId

	// no validation rules for EventId

	// no validation rules for Section

	// no validation rules for SeatIndex

	if len(errors) > 0 {
		return SagaPayReqMultiError(errors)
	}

	return nil
}

// SagaPayReqMultiError is an error wrapping multiple validation errors
// returned by SagaPayReq.ValidateAll() if the designated constraints aren't met.
type SagaPayReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SagaPayReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SagaPayReqMultiError) AllErrors() []error { return m }

// SagaPayReqValidationError is the validation error returned by
// SagaPayReq.Validate if the designated constraints aren't met.
type SagaPayReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SagaPayReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SagaPayReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SagaPayReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SagaPayReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SagaPayReqValidationError) ErrorName() string { return "SagaPayReqValidationError" }

// Error satisfies the builtin error interface
func (e SagaPayReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSagaPayReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SagaPayReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SagaPayReqValidationError{}

// Validate checks the field values on SagaPayResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SagaPayResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SagaPayResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SagaPayRespMultiError, or
// nil if none found.
func (m *SagaPayResp) ValidateAll() error {
	return m.validate(true)
}

func (m *SagaPayResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return SagaPayRespMultiError(errors)
	}

	return nil
}

// SagaPayRespMultiError is an error wrapping multiple validation errors
// returned by SagaPayResp.ValidateAll() if the designated constraints aren't met.
type SagaPayRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SagaPayRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SagaPayRespMultiError) AllErrors() []error { return m }

// SagaPayRespValidationError is the validation error returned by
// SagaPayResp.Validate if the designated constraints aren't met.
type SagaPayRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SagaPayRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SagaPayRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SagaPayRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SagaPayRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SagaPayRespValidationError) ErrorName() string { return "SagaPayRespValidationError" }

// Error satisfies the builtin error interface
func (e SagaPayRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSagaPayResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SagaPayRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SagaPayRespValidationError{}

// Validate checks the field values on PayReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PayReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayReq with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PayReqMultiError, or nil if none found.
func (m *PayReq) ValidateAll() error {
	return m.validate(true)
}

func (m *PayReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOrderSn()) < 1 {
		err := PayReqValidationError{
			field:  "OrderSn",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := PayReqValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PayReqMultiError(errors)
	}

	return nil
}

// PayReqMultiError is an error wrapping multiple validation errors returned by
// PayReq.ValidateAll() if the designated constraints aren't met.
type PayReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayReqMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayReqMultiError) AllErrors() []error { return m }

// PayReqValidationError is the validation error returned by PayReq.Validate if
// the designated constraints aren't met.
type PayReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayReqValidationError) ErrorName() string { return "PayReqValidationError" }

// Error satisfies the builtin error interface
func (e PayReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayReqValidationError{}

// Validate checks the field values on PayResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PayResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PayResp with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PayRespMultiError, or nil if none found.
func (m *PayResp) ValidateAll() error {
	return m.validate(true)
}

func (m *PayResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if len(errors) > 0 {
		return PayRespMultiError(errors)
	}

	return nil
}

// PayRespMultiError is an error wrapping multiple validation errors returned
// by PayResp.ValidateAll() if the designated constraints aren't met.
type PayRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PayRespMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PayRespMultiError) AllErrors() []error { return m }

// PayRespValidationError is the validation error returned by PayResp.Validate
// if the designated constraints aren't met.
type PayRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PayRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PayRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PayRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PayRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PayRespValidationError) ErrorName() string { return "PayRespValidationError" }

// Error satisfies the builtin error interface
func (e PayRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPayResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PayRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PayRespValidationError{}
