// rpc/payment/payment.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: payment.proto

package rpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- DTM Saga 通用请求体 ---
// 包含了支付和出票所需要的所有参数
type SagaPayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`  // 订单号 (用于日志跟踪和防重)
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 用户ID (用于扣减 user_wallet)
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                  // 支付金额 (单位：分)
	SeatId        int64                  `protobuf:"varint,4,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`    // 座位ID (支付侧不用，但Order侧需要)
	EventId       int64                  `protobuf:"varint,5,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 场次ID (支付侧不用，但Order侧需要)
	Section       string                 `protobuf:"bytes,6,opt,name=section,proto3" json:"section,omitempty"`                 // 为了支持BitMap所做的优化（支付侧不用，但Order侧需要）
	SeatIndex     int64                  `protobuf:"varint,7,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaPayReq) Reset() {
	*x = SagaPayReq{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaPayReq) ProtoMessage() {}

func (x *SagaPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaPayReq.ProtoReflect.Descriptor instead.
func (*SagaPayReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *SagaPayReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *SagaPayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SagaPayReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SagaPayReq) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *SagaPayReq) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *SagaPayReq) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *SagaPayReq) GetSeatIndex() int64 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

type SagaPayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaPayResp) Reset() {
	*x = SagaPayResp{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaPayResp) ProtoMessage() {}

func (x *SagaPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaPayResp.ProtoReflect.Descriptor instead.
func (*SagaPayResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *SagaPayResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SagaPayResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 支付请求体 (供 API 层调用)
type PayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"` // 订单号，必填且不能为空
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`   // 核心安全校验：必须传入 user_id，防止水平越权
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PayReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResp) Reset() {
	*x = PayResp{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResp) ProtoMessage() {}

func (x *PayResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResp.ProtoReflect.Descriptor instead.
func (*PayResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PayResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\x1a\x1avalidate/rpcvalidate.proto\"\xc5\x01\n" +
	"\n" +
	"SagaPayReq\x12\x19\n" +
	"\border_sn\x18\x01 \x01(\tR\aorderSn\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x17\n" +
	"\aseat_id\x18\x04 \x01(\x03R\x06seatId\x12\x19\n" +
	"\bevent_id\x18\x05 \x01(\x03R\aeventId\x12\x18\n" +
	"\asection\x18\x06 \x01(\tR\asection\x12\x1d\n" +
	"\n" +
	"seat_index\x18\a \x01(\x03R\tseatIndex\"A\n" +
	"\vSagaPayResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x06PayReq\x12\"\n" +
	"\border_sn\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\aorderSn\x12 \n" +
	"\auser_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x06userId\"=\n" +
	"\aPayResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9d\x01\n" +
	"\aPayment\x123\n" +
	"\x06Deduct\x12\x13.payment.SagaPayReq\x1a\x14.payment.SagaPayResp\x123\n" +
	"\x06Refund\x12\x13.payment.SagaPayReq\x1a\x14.payment.SagaPayResp\x12(\n" +
	"\x03Pay\x12\x0f.payment.PayReq\x1a\x10.payment.PayRespB\rZ\vpayment/rpcb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_proto_goTypes = []any{
	(*SagaPayReq)(nil),  // 0: payment.SagaPayReq
	(*SagaPayResp)(nil), // 1: payment.SagaPayResp
	(*PayReq)(nil),      // 2: payment.PayReq
	(*PayResp)(nil),     // 3: payment.PayResp
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.Payment.Deduct:input_type -> payment.SagaPayReq
	0, // 1: payment.Payment.Refund:input_type -> payment.SagaPayReq
	2, // 2: payment.Payment.Pay:input_type -> payment.PayReq
	1, // 3: payment.Payment.Deduct:output_type -> payment.SagaPayResp
	1, // 4: payment.Payment.Refund:output_type -> payment.SagaPayResp
	3, // 5: payment.Payment.Pay:output_type -> payment.PayResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
