// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginRegisterResp struct {
	UserId       int64  `json:"user_id"`
	Token        string `json:"token"`
	TokenExpire  int64  `json:"token_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserDetailResp struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}
