// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginRegisterResp struct {
	Token        string `json:"token,optional"`
	TokenExpire  int64  `json:"token_expire,optional"`
	RefreshToken string `json:"refresh_token,optional"`
}

type LoginReq struct {
	Mobile   string `json:"mobile,optional"`
	Password string `json:"password,optional"`
}

type LogoutReq struct {
	RefreshToken string `json:"refresh_token,optional" validate:"required,min=1"`
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token,optional"`
}

type RefreshResp struct {
	AccessToken  string `json:"access_token,optional"`
	AccessExpire int64  `json:"access_expire,optional"`
	RefreshToken string `json:"refresh_token,optional"`
	RefreshAfter int64  `json:"refresh_after,optional"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile,optional" validate:"required"`
	Password string `json:"password,optional" validate:"required,min=6"`
	Nickname string `json:"nickname,optional" validate:"required,min=5,max=20"`
	Sex      int64  `json:"sex,optional" default:"0" validate:"oneof=0 1 2"` // 0未知 1男 2女
	Avatar   string `json:"avatar,optional" validate:"omitempty,url"`
	Info     string `json:"info,optional" validate:"omitempty,max=255"`
}

type UserDetailResp struct {
	Id       int64  `json:"id,optional"`
	Mobile   string `json:"mobile,optional"`
	Nickname string `json:"nickname,optional"`
	Sex      int64  `json:"sex,optional"`
	Avatar   string `json:"avatar,optional"`
	Info     string `json:"info,optional"`
}
