// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: payment.proto

package payment

import (
	"context"
	rpc2 "tickets-hunter/app/payment/cmd/rpc/payment/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PayReq      = rpc2.PayReq
	PayResp     = rpc2.PayResp
	SagaPayReq  = rpc2.SagaPayReq
	SagaPayResp = rpc2.SagaPayResp

	Payment interface {
		// Saga 步骤1 正向操作：扣减余额
		Deduct(ctx context.Context, in *SagaPayReq, opts ...grpc.CallOption) (*SagaPayResp, error)
		// Saga 步骤2 补偿操作：退还余额
		Refund(ctx context.Context, in *SagaPayReq, opts ...grpc.CallOption) (*SagaPayResp, error)
		// API 层调用的支付接口
		Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

// Saga 步骤1 正向操作：扣减余额
func (m *defaultPayment) Deduct(ctx context.Context, in *SagaPayReq, opts ...grpc.CallOption) (*SagaPayResp, error) {
	client := rpc2.NewPaymentClient(m.cli.Conn())
	return client.Deduct(ctx, in, opts...)
}

// Saga 步骤2 补偿操作：退还余额
func (m *defaultPayment) Refund(ctx context.Context, in *SagaPayReq, opts ...grpc.CallOption) (*SagaPayResp, error) {
	client := rpc2.NewPaymentClient(m.cli.Conn())
	return client.Refund(ctx, in, opts...)
}

// API 层调用的支付接口
func (m *defaultPayment) Pay(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	client := rpc2.NewPaymentClient(m.cli.Conn())
	return client.Pay(ctx, in, opts...)
}
