// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package ticket_event

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	ticketEventFieldNames          = builder.RawFieldNames(&TicketEvent{})
	ticketEventRows                = strings.Join(ticketEventFieldNames, ",")
	ticketEventRowsExpectAutoSet   = strings.Join(stringx.Remove(ticketEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	ticketEventRowsWithPlaceHolder = strings.Join(stringx.Remove(ticketEventFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	ticketEventModel interface {
		Insert(ctx context.Context, data *TicketEvent) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TicketEvent, error)
		Update(ctx context.Context, data *TicketEvent) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTicketEventModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TicketEvent struct {
		Id            int64     `db:"id"`
		Title         string    `db:"title"`           // 演唱会标题
		CoverUrl      string    `db:"cover_url"`       // 海报封面图
		ShowTime      time.Time `db:"show_time"`       // 演出开始时间
		Venue         string    `db:"venue"`           // 场馆名称
		SaleStartTime time.Time `db:"sale_start_time"` // 开售时间(到达此时间才允许锁座)
		SaleEndTime   time.Time `db:"sale_end_time"`   // 停售时间
		Status        int64     `db:"status"`          // 状态: 0下架, 1上架
		CreateTime    time.Time `db:"create_time"`
		UpdateTime    time.Time `db:"update_time"`
	}
)

func newTicketEventModel(conn sqlx.SqlConn) *defaultTicketEventModel {
	return &defaultTicketEventModel{
		conn:  conn,
		table: "`ticket_event`",
	}
}

func (m *defaultTicketEventModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTicketEventModel) FindOne(ctx context.Context, id int64) (*TicketEvent, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", ticketEventRows, m.table)
	var resp TicketEvent
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTicketEventModel) Insert(ctx context.Context, data *TicketEvent) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, ticketEventRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.CoverUrl, data.ShowTime, data.Venue, data.SaleStartTime, data.SaleEndTime, data.Status)
	return ret, err
}

func (m *defaultTicketEventModel) Update(ctx context.Context, data *TicketEvent) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, ticketEventRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.CoverUrl, data.ShowTime, data.Venue, data.SaleStartTime, data.SaleEndTime, data.Status, data.Id)
	return err
}

func (m *defaultTicketEventModel) tableName() string {
	return m.table
}
