// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: mq_message.proto

package mq_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MQMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MQMessage) Reset() {
	*x = MQMessage{}
	mi := &file_mq_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MQMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQMessage) ProtoMessage() {}

func (x *MQMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mq_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQMessage.ProtoReflect.Descriptor instead.
func (*MQMessage) Descriptor() ([]byte, []int) {
	return file_mq_message_proto_rawDescGZIP(), []int{0}
}

func (x *MQMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MQMessage) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MQMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_mq_message_proto protoreflect.FileDescriptor

const file_mq_message_proto_rawDesc = "" +
	"\n" +
	"\x10mq_message.proto\x12\x06mq_msg\"M\n" +
	"\tMQMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04dataB\n" +
	"Z\b./mq_msgb\x06proto3"

var (
	file_mq_message_proto_rawDescOnce sync.Once
	file_mq_message_proto_rawDescData []byte
)

func file_mq_message_proto_rawDescGZIP() []byte {
	file_mq_message_proto_rawDescOnce.Do(func() {
		file_mq_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mq_message_proto_rawDesc), len(file_mq_message_proto_rawDesc)))
	})
	return file_mq_message_proto_rawDescData
}

var file_mq_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mq_message_proto_goTypes = []any{
	(*MQMessage)(nil), // 0: mq_msg.MQMessage
}
var file_mq_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mq_message_proto_init() }
func file_mq_message_proto_init() {
	if File_mq_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mq_message_proto_rawDesc), len(file_mq_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mq_message_proto_goTypes,
		DependencyIndexes: file_mq_message_proto_depIdxs,
		MessageInfos:      file_mq_message_proto_msgTypes,
	}.Build()
	File_mq_message_proto = out.File
	file_mq_message_proto_goTypes = nil
	file_mq_message_proto_depIdxs = nil
}
