// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ticket.proto

package ticketservice

import (
	"context"

	"tickets-hunter/app/ticket/cmd/rpc/ticket/rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EventInfo        = rpc.EventInfo
	GetEventListReq  = rpc.GetEventListReq
	GetEventListResp = rpc.GetEventListResp
	GetSeatInfoReq   = rpc.GetSeatInfoReq
	GetSeatListReq   = rpc.GetSeatListReq
	GetSeatListResp  = rpc.GetSeatListResp
	LockSeatReq      = rpc.LockSeatReq
	LockSeatResp     = rpc.LockSeatResp
	SeatInfo         = rpc.SeatInfo

	TicketService interface {
		// 获取演唱会场次列表 (供 API 层调用)
		GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error)
		// 获取指定场次的座位图及状态 (供 API 层调用)
		GetSeatList(ctx context.Context, in *GetSeatListReq, opts ...grpc.CallOption) (*GetSeatListResp, error)
		// 锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
		LockSeat(ctx context.Context, in *LockSeatReq, opts ...grpc.CallOption) (*LockSeatResp, error)
		// 获取座位信息 (供 Order RPC 内部调用)
		GetSeatInfo(ctx context.Context, in *GetSeatInfoReq, opts ...grpc.CallOption) (*SeatInfo, error)
	}

	defaultTicketService struct {
		cli zrpc.Client
	}
)

func NewTicketService(cli zrpc.Client) TicketService {
	return &defaultTicketService{
		cli: cli,
	}
}

// 获取演唱会场次列表 (供 API 层调用)
func (m *defaultTicketService) GetEventList(ctx context.Context, in *GetEventListReq, opts ...grpc.CallOption) (*GetEventListResp, error) {
	client := rpc.NewTicketServiceClient(m.cli.Conn())
	return client.GetEventList(ctx, in, opts...)
}

// 获取指定场次的座位图及状态 (供 API 层调用)
func (m *defaultTicketService) GetSeatList(ctx context.Context, in *GetSeatListReq, opts ...grpc.CallOption) (*GetSeatListResp, error) {
	client := rpc.NewTicketServiceClient(m.cli.Conn())
	return client.GetSeatList(ctx, in, opts...)
}

// 锁定座位 (内部隐藏接口，不暴露给前端，仅供 Order RPC 调用)
func (m *defaultTicketService) LockSeat(ctx context.Context, in *LockSeatReq, opts ...grpc.CallOption) (*LockSeatResp, error) {
	client := rpc.NewTicketServiceClient(m.cli.Conn())
	return client.LockSeat(ctx, in, opts...)
}

// 获取座位信息 (供 Order RPC 内部调用)
func (m *defaultTicketService) GetSeatInfo(ctx context.Context, in *GetSeatInfoReq, opts ...grpc.CallOption) (*SeatInfo, error) {
	client := rpc.NewTicketServiceClient(m.cli.Conn())
	return client.GetSeatInfo(ctx, in, opts...)
}
