// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	order "tickets-hunter/app/order/cmd/api/internal/handler/order"
	"tickets-hunter/app/order/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建抢票订单(锁座+创单)
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				// 获取订单详情
				Method:  http.MethodGet,
				Path:    "/detail",
				Handler: order.GetOrderDetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/order/v1"),
	)
}
